apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::417071062939:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XQJO43FLSE0T
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::417071062939:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-23T00:02:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "795"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 28098fd4-dd19-4378-a1d4-0e82f8c08dcb
